### PR TITLE
Edits and updates

### PR DESCRIPTION
**Pull request by jenschlot**
### Description

Removed template statements and cleaned up some data

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [x] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Edits and text improvements to the reference architecture.

---

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

### CODE REVIEW

**Comment by christoc-ibm** [comment]
@michaelbowler - Jenifer's changes look good to me. You can go ahead and approve/merge (if you have appropriate access). For the kind of changes that she made (doc changes), I don't think it's necessary for a developer to review.

Not sure why the checks are failing, though.

**Comment by huayuenh** [comment]
> @michaelbowler - Jenifer's changes look good to me. You can go ahead and approve/merge (if you have appropriate access). For the kind of changes that she made (doc changes), I don't think it's necessary for a developer to review.
> 
> Not sure why the checks are failing, though.

Currently looking into these failures. Could be a case of not being a member of the repo, in which case I'll copy the changes into PR myself

**Comment by huayuenh** [comment]
See https://github.com/terraform-ibm-modules/terraform-ibm-devsecops-alm/pull/106

**Comment by huayuenh** [comment]
> @huayuenh "You can go ahead and approve/merge (if you have appropriate access)." Nope, don't have the privs> @jenschlot did you say in yesterday's meeting that Allen might be able to help?

Merged in https://github.com/terraform-ibm-modules/terraform-ibm-devsecops-alm/pull/106

**Comment by christoc-ibm** [comment]
Thank you, @huayuenh! 

@jenschlot - Can you please close this PR? The updates were merged under PR 106. I'm unable to close this due to access limitations.

**Pull request closed without merging**
